#!/usr/bin/env bash
# Displays information about subdomains

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    
    local record=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print}')
    
    local record_type=$(echo "$record" | awk '{print $4}')
    local destination=$(echo "$record" | awk '{print $5}')
    
    # Display the information
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
        get_subdomain_info "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    get_subdomain_info "$1" "$2"
fi
