#!/usr/bin/env bash
# Transfers a file from our client to a server
# Arguments:
#   1. Path to the file to be transferred
#   2. IP of the server we want to transfer the file to
#   3. Username that scp connects with
#   4. Path to the SSH private key that scp uses to authenticate

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
