#!/bin/bash
# This script installs and configures Nginx to serve a "Hello World!" page.

# Update the package list and Install Nginx
apt-get update -y
apt-get install nginx -y

# Create a custom index.html
echo "Hello World!" >/var/www/html/index.html

# Restart Nginx using init.d (not systemctl)
sudo /etc/init.d/nginx restart
