#!/usr/bin/env bash
# Configures Nginx server for redirection

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

service nginx restart
