#!/usr/bin/env bash
# Install and configure HAproxy as a load balancer on a new Ubuntu machine

# Update packages and install HAproxy
apt-get update
apt-get install -y haproxy

# Configure HAproxy
cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.224.63.237:80 check
    server web-02 52.86.3.5:80 check
EOF

# Enable HAproxy to be started by init script
echo "ENABLED=1" > /etc/default/haproxy

# Restart HAproxy
service haproxy restart

# Ensure HAproxy starts on boot
systemctl enable haproxy
