#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

MYSQL_USER="root"
mysqldump -u "$MYSQL_USER" -p"$1" --all-databases >backup.sql
tar -czf "$(date +"%d-%m-%Y")" backup.sql
