#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

# Check if password argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# Set variables
MYSQL_USER="root"
MYSQL_PASS="$1"
DATE=$(date +"%d-%m-%Y")

# Generate MySQL dump
mysqldump -u "$MYSQL_USER" -p"$MYSQL_PASS" --all-databases >backup.sql

# Create compressed archive
tar -czf "$DATE.tar.gz" backup.sql

# Remove the uncompressed SQL file
rm backup.sql
