#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 of all active IPv4 IPs

# Modify the Nginx configuration to listen on port 80
sed -i 's/8080 default_server/ 80 default_server/' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
