#!/bin/bash
temp_file=$(mktemp)

ls -a1p | grep -v -E "^\.$|^\.\.$" | sort -k1.1,1.1 -k1.2,1.2 > "$temp_file"

sed -e "s/$/,/" -i "$temp_file"

cat "$temp_file" | tr -d "\n" && echo

rm "$temp_file"

