#!/usr/bin/env bash
# This script displays the username, user ID, and home directory from the /etc/passwd file.

while IFS=":" read -r username
do
    echo "$username" | cut -d":" -f1,3,6
done < /etc/passwd
