#!/usr/bin/env bash
# This script parses an Apache log file,
# displays the visitor IP and HTTP status code,
# sorts the results by the number of occurrences,
# and displays the top 10 IPs and their status codes.

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
